---
pool:
  vmImage: ubuntu-latest

trigger:
  - main

parameters:
  - name: version
    displayName: version
    type: string
    default: v1.0

steps:
- script: "echo ${{ parameters.image }}-$(Build.BuildId)"
  displayname: say hello